# Setup
title:        "Rand/eng works"
description:  "Technical guides, publications and snippets for easy deployment and development"
tagline:      ""
baseurl:      ""
url:          CarolinaFernandez.github.io

# About/contact
author:
  name:             Carolina Fern&aacute;ndez
  url:              CarolinaFernandez.github.io
  github:           CarolinaFernandez
  google_analytics: UA-92777337-1
  disqus:           cf-github
  linkedin:         cfermart
  twitter:          cfermart
  orcid:            0000-0003-1865-7177
  google_scholar:   JgfJktkAAAAJ

paginate:      10
paginate_path: "/blog/:num/"

# Gems
gems:
  - jekyll-paginate
  - rouge

exclude: ["cv"]

# Post configuration
excerpt_separator: <!--more-->

# Headers
webrick:
  headers:
    Strict-Transport-Security: max-age=2592000

# Include extra folders
include:
    - _pages

# Markdown parsing
markdown: kramdown
highlighter: rouge

# More options at https://github.com/jekyll/jekyll/issues/4619
# Custom MD converter:
    # https://gist.github.com/leonardfactory/5532926#file-redcarpet_pygments-rb-L3
    # https://jekyllrb.com/docs/plugins/#converters
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    format_style: 'div'
    # Rouge Options: https://kramdown.gettalong.org/syntax_highlighter/rouge.html, https://github.com/jneen/rouge/blob/master/README.md
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
#    formatter: 'Rouge::Formatters::HTMLLinewise'
