# Setup
title:        "Snippets on technical thoughts"
description:  Carolina Fernandez
tagline:      ""
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Carolina Fernandez
  url:        CarolinaFernandez.github.io
  github:     CarolinaFernandez

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
