# Setup
title:        "Snippets on technical thoughts"
description:  "Short guides and code snippets for common development and deployment questions"
tagline:      ""
baseurl:      ""
url:          CarolinaFernandez.github.io
paginate:     1

# About/contact
author:
  name:       Carolina Fernandez
  url:        CarolinaFernandez.github.io
  github:     CarolinaFernandez

# Gems
gems:
  - jekyll-paginate

excerpt_separator: <!--more-->

# Headers
webrick:
  headers:
    Strict-Transport-Security: max-age=2592000

# Include extra folders
include:
    - _pages

# Markdown parsing
markdown: kramdown
